services:
  - type: web
    name: aritana
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn aritana.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: aritana.onrender.com
    
databases:
  - name: aritana-db
    databaseName: aritana
    user: aritana 