# Generated by Django 5.2.4 on 2025-09-21 00:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Embarcação')),
                ('tipo', models.CharField(choices=[('legal', 'Embarcação Legal'), ('fiscal', 'Fiscalização'), ('ilegal', 'Embarcação Ilegal')], default='legal', max_length=10, verbose_name='Tipo')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Embarcação',
                'verbose_name_plural': 'Embarcações',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100, verbose_name='Região')),
                ('mes', models.DateField(verbose_name='Mês de Referência')),
                ('embarcacoes_legais', models.PositiveIntegerField(default=0, verbose_name='Embarcações Legais')),
                ('embarcacoes_ilegais', models.PositiveIntegerField(default=0, verbose_name='Embarcações Ilegais')),
                ('total_fiscalizacoes', models.PositiveIntegerField(default=0, verbose_name='Total de Fiscalizações')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Análise Regional',
                'verbose_name_plural': 'Análises Regionais',
                'ordering': ['-mes'],
                'unique_together': {('regiao', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ImagemEmbarcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='embarcacoes/', verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Upload')),
                ('status_analise', models.CharField(choices=[('pendente', 'Pendente'), ('analisada', 'Analisada'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status da Análise')),
                ('embarcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='embarcacoes.embarcacao', verbose_name='Embarcação')),
            ],
            options={
                'verbose_name': 'Imagem da Embarcação',
                'verbose_name_plural': 'Imagens das Embarcações',
                'ordering': ['-data_upload'],
            },
        ),
    ]
