# Generated by Django 4.2.23 on 2025-06-20 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regiao', models.CharField(max_length=100, unique=True, verbose_name='Nome da Região')),
                ('lat_min', models.FloatField(verbose_name='Latitude Mínima')),
                ('lat_max', models.FloatField(verbose_name='Latitude Máxima')),
                ('lon_min', models.FloatField(verbose_name='Longitude Mínima')),
                ('lon_max', models.FloatField(verbose_name='Longitude Máxima')),
                ('total_embarcacoes', models.PositiveIntegerField(default=0, verbose_name='Total de Embarcações')),
                ('embarcacoes_legais', models.PositiveIntegerField(default=0, verbose_name='Embarcações Legais')),
                ('embarcacoes_ilegais', models.PositiveIntegerField(default=0, verbose_name='Embarcações Ilegais')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estatísticas da Região',
                'verbose_name_plural': 'Estatísticas das Regiões',
                'ordering': ['nome_regiao'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseEmbarcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='embarcacoes/%Y/%m/%d/', verbose_name='Imagem da Embarcação')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('status', models.CharField(choices=[('legal', 'Legal'), ('ilegal', 'Ilegal'), ('em_analise', 'Em Análise')], default='em_analise', max_length=20, verbose_name='Status de Legalidade')),
                ('probabilidade', models.FloatField(help_text='Probabilidade em porcentagem (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Probabilidade')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('data_analise', models.DateTimeField(auto_now_add=True, verbose_name='Data da Análise')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('modelo_ia_utilizado', models.CharField(default='YOLOv8', max_length=100, verbose_name='Modelo de IA Utilizado')),
                ('tempo_processamento', models.FloatField(blank=True, help_text='Tempo de processamento em segundos', null=True, verbose_name='Tempo de Processamento (s)')),
            ],
            options={
                'verbose_name': 'Análise de Embarcação',
                'verbose_name_plural': 'Análises de Embarcações',
                'ordering': ['-data_analise'],
                'indexes': [models.Index(fields=['status'], name='embarcacoes_status_20e498_idx'), models.Index(fields=['data_analise'], name='embarcacoes_data_an_cfa5a9_idx'), models.Index(fields=['latitude', 'longitude'], name='embarcacoes_latitud_3e77d2_idx')],
            },
        ),
    ]
