# Generated by Django 4.2.23 on 2025-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarcacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseembarcacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='embarcacoes/%Y/%m/%d/', verbose_name='Imagem da Embarcação'),
        ),
    ]
