# Generated by Django 5.2.4 on 2025-09-21 18:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarcacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='embarcacao',
            name='regiao',
            field=models.CharField(choices=[('belem_centro', 'Belém Centro'), ('icoaraci', 'Icoaraci'), ('outeiro', 'Outeiro'), ('mosqueiro', 'Mosqueiro'), ('cotijuba', 'Cotijuba'), ('guama', 'Guamá'), ('ananindeua', 'Ananindeua')], default='belem_centro', max_length=20, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='confiabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confiabilidade'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='data_analise',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='resultado_analise',
            field=models.JSONField(blank=True, null=True, verbose_name='Resultado da Análise'),
        ),
        migrations.AlterField(
            model_name='embarcacao',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-2.0')), django.core.validators.MaxValueValidator(Decimal('-0.5'))], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='embarcacao',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-49.0')), django.core.validators.MaxValueValidator(Decimal('-47.5'))], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='imagemembarcacao',
            name='imagem',
            field=models.ImageField(help_text='Formatos aceitos: JPG, PNG, JPEG. Máximo 10MB', upload_to='embarcacoes/%Y/%m/%d/', verbose_name='Imagem'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['tipo'], name='embarcacoes_tipo_5c2cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['regiao'], name='embarcacoes_regiao_65a615_idx'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['ativa'], name='embarcacoes_ativa_1262a7_idx'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['data_registro'], name='embarcacoes_data_re_d4e95d_idx'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['tipo', 'regiao'], name='embarcacoes_tipo_a9f66a_idx'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['data_registro', 'ativa'], name='embarcacoes_data_re_6ce397_idx'),
        ),
        migrations.AddIndex(
            model_name='embarcacao',
            index=models.Index(fields=['latitude', 'longitude'], name='embarcacoes_latitud_a9cfe8_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemembarcacao',
            index=models.Index(fields=['status_analise'], name='embarcacoes_status__6092b0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemembarcacao',
            index=models.Index(fields=['data_upload'], name='embarcacoes_data_up_0598b2_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemembarcacao',
            index=models.Index(fields=['embarcacao', 'status_analise'], name='embarcacoes_embarca_34a21d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemembarcacao',
            index=models.Index(fields=['data_upload', 'status_analise'], name='embarcacoes_data_up_8b5534_idx'),
        ),
    ]
