# Generated by Django 5.2.4 on 2025-10-04 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarcacoes', '0002_optimize_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemembarcacao',
            name='erro_processamento',
            field=models.TextField(blank=True, verbose_name='Erro no Processamento'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Job ID'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='mensagem_status',
            field=models.CharField(blank=True, max_length=500, verbose_name='Mensagem de Status'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='progresso',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progresso (%)'),
        ),
        migrations.AddField(
            model_name='imagemembarcacao',
            name='resource_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Resource ID'),
        ),
        migrations.AlterField(
            model_name='imagemembarcacao',
            name='status_analise',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('analisada', 'Analisada'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('erro', 'Erro no Processamento')], default='pendente', max_length=15, verbose_name='Status da Análise'),
        ),
        migrations.AddIndex(
            model_name='imagemembarcacao',
            index=models.Index(fields=['job_id'], name='embarcacoes_job_id_704bec_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemembarcacao',
            index=models.Index(fields=['resource_id'], name='embarcacoes_resourc_316adb_idx'),
        ),
    ]
