# Generated by Django 5.2.4 on 2025-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarcacoes', '0003_imagemembarcacao_erro_processamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemembarcacao',
            name='tentativas_consulta',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de Consulta'),
        ),
    ]
